name: 'Test'

on:
  pull_request:
  merge_group:

jobs:
  check:
    name: Check all
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: ./

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - run: npx nx run-many --target=lint
      - run: npx nx run-many --target=build

      - name: Sleep for 2 minutes
        run: sleep 120
